FROM jenkins/jenkins:lts-jdk17

USER root

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates git openssh-client \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# (선택) 디버깅용 확인
RUN java -version
